build:
   image: gitlab/dind
   
services:
  - docker:dind
  
variables:
#  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
   IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
